#!/usr/bin/env python3
#_*_ coding:utf-8 _*_

import os,signal,time

message = "Hello, Process 2. I'm Process 1 :)"

def receive_signal(signum, stack): 
	time.sleep(2)   
	print('Received:', signum)

def write (words):
	file = open('/tmp/Chat.txt','w')
	file.write(words)
	file.close()


signal.signal(signal.SIGUSR1, receive_signal)


print('My PID is:', os.getpid())
write(str(os.getpid()))
target = input("Please enter the pid of process2:")

while True:
	write(message)	
	os.kill(int(target),signal.SIGUSR2)
	print('Writing...')
	signal.pause()




